# Generated by Django 4.2.18 on 2025-01-29 18:28

from django.db import migrations

def assign_admin_to_group(apps, schema_editor):
    User = apps.get_model("auth", "User")
    Group = apps.get_model("auth", "Group")

    # Ensure "Admin" group exists
    admin_group, created = Group.objects.get_or_create(name="Admin")

    # Assign all superusers to the "Admin" group
    superusers = User.objects.filter(is_superuser=True)
    for user in superusers:
        user.groups.add(admin_group)

class Migration(migrations.Migration):

    dependencies = [
        ('articles', '0004_useractivitylog_articleversion'),
    ]

    operations = [
        migrations.RunPython(assign_admin_to_group),
    ]
