services:
  redis:
    image: redis
    restart: always
    ports:
      - "6379:6379"

  backend:
    build: .
    depends_on:
      - redis
    env_file:
      - .env 
    environment:
      DATABASE_URL: ${DATABASE_URL}
      REDIS_HOST: redis
      REDIS_PORT: 6379
    ports:
      - "8000:8000"
